######################################################################
# Automatically generated by qmake (3.0) Wed Jan 12 14:52:39 2022
######################################################################

TEMPLATE = app
TARGET = refresh
INCLUDEPATH += .

# Input
HEADERS += cli.h
SOURCES += cli.cpp refresh.cpp
LIBS += -L/tc/arm-nickel-linux-gnueabihf/arm-nickel-linux-gnueabihf/sysroot/usr/lib -ldl
